# Generated by Django 3.1.6 on 2021-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(default='Image', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery/'),
        ),
    ]
