# Generated by Django 3.1.6 on 2021-02-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210215_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
    ]
