# Generated by Django 3.1.6 on 2021-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactheader',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterField(
            model_name='contactheader',
            name='promo_text',
            field=models.TextField(max_length=1024),
        ),
    ]
