# Generated by Django 3.1.6 on 2021-02-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Pinterest', 'Pinterest'), ('Snapchat', 'Snapchat'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('YouTube', 'YouTube')], max_length=150, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': "Social Media's",
            },
        ),
    ]
