# Generated by Django 3.1.6 on 2021-02-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logotype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logotype',
            old_name='logotype',
            new_name='image',
        ),
        migrations.AddField(
            model_name='logotype',
            name='name',
            field=models.CharField(default='logotype', max_length=150, null=True),
        ),
    ]
