# Generated by Django 3.1.6 on 2021-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210212_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Pinterest', 'Pinterest'), ('Snapchat', 'Snapchat'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('YouTube', 'YouTube')], max_length=150, null=True),
        ),
    ]
