# Generated by Django 3.1.6 on 2021-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210212_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Slide', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
            ],
            options={
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
