# Generated by Django 3.1.6 on 2021-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='title',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='slides',
            name='name',
            field=models.CharField(default='Slide ', editable=False, max_length=50),
        ),
    ]
