# Generated by Django 3.1.6 on 2021-02-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210212_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': "Social Media's"},
        ),
    ]
